Add size change automation to Enlarge/reduce
DFreds/dfreds-convenient-effects pull request #113
Opened 2022-01-20 21:07 UTC by Maravedis

This MR aims to provide automation of token sizes for the spell Enlarge/Reduce.

The token sizes and actor sizes label are [taken from the DND5e game system module](https://gitlab.com/foundrynet/dnd5e/-/blob/master/module/config.js#L277).

This functionality needs "Size adjustment with flags" to be enabled in ATL.

Known issues:
* Since the size changes are dynamic, the fact that they are ATL dependent doesn't appear on the UI.
* When the token changes size, the little floating text `+Enlarge` or `-Enlarge` doesn't appear.

I only saw Issue #5 and your response to it after I was done with this, so I'd understand perfectly if it doesn't fit your vision for the module. LMK what you think :) .

2022-01-21 23:14 UTC, DFreds commented
Yeah, I tried doing this myself but ultimately had some issues. I think this is probably the way to go. I'm fine with both issues you described.

FYI, I resolved the conflict with the other MR #114... Haven't done that before, so make sure you pull before doing any other updates. I'll just have a couple of comments

2022-01-21 23:21 UTC, DFreds requested changes

2022-01-21 23:21 UTC, DFreds commented on scripts/effects/dynamic-effects-adder.js
> +
Unnecessary new line

2022-01-21 23:21 UTC, DFreds commented on scripts/effects/dynamic-effects-adder.js
> +  _addEnlargeReduceEffect(effect, actor) {
I think I'd prefer to have these handled separately with some common private methods as needed

2022-01-22 10:40 UTC, Maravedis commented
> FYI, I resolved the conflict with the other MR #114... Haven't done that before, so make sure you pull before doing any other updates. I'll just have a couple of comments

I think I'll just rebase / force-push to keep the history clean.

2022-01-22 11:10 UTC, Maravedis commented
Another thing about this: it requires ATL >= 0.3.06, because of a bug affecting ATL size flags in previous version.

2022-01-23 00:26 UTC, DFreds commented
This looks good. Thanks!

2022-01-23 00:27 UTC, merged